server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?prepareThreshold=0
    username: postgres.dbkbdshdgxjqldbavbco
    password: "***REMOVED-DB-PASSWORD***"

app:
  finlight:
    api-key: ***REMOVED-ADMIN-API-KEY***
  genai:
    url: https://finswipe.zeabur.app
    user: fin
    password: "1234"
  admin:
    api-key: ***REMOVED-FINLIGHT-KEY***
