server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://REMOVED-DB-HOST:5432/finswipe
    username: finswipe
    password: "***REMOVED-DB-PASSWORD***"

app:
  finlight:
    api-key: ***REMOVED-ADMIN-API-KEY***
  genai:
    url: http://localhost:8000
    user: fin
    password: "1234"
  admin:
    api-key: ***REMOVED-FINLIGHT-KEY***
