server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://finswipe-db.c7gaqsqoq86j.ap-northeast-2.rds.amazonaws.com:5432/finswipe
    username: finswipe
    password: "qlfejtmflrm1emd!"

app:
  finlight:
    api-key: sk_27a33efd0dd80ec7f839b40b57f92d5401e18df70c784bfcc628a3d7c9fb8ad0
  genai:
    url: http://localhost:8000
    user: fin
    password: "1234"
  admin:
    api-key: l_NlyedZlKhUgtNDLMx-Z3vq00QAogNeJZ_keA4Fjng
